### ISSUE TITLE
Change output window

### ISSUE THREAD

**Issue by Goss444** [BelegCufea/PrettyReputation#1]
Great addon thank you. I would love to be able to pick what chat window the output is sent to. At its basic being able to send it to ChatFrame1 to n would be nice or even be able to send it to all the windows that display loot or reputation changes.

Thank you.

**Comment by BelegCufea** [comment]
Thank you.

I was just looking into how to do it.

I included LibSink without fully understanding what I was doing; that's just my usual approach to these kinds of things. It appears that it can be done in some way, so I'll look into it further."

Have a great day!

**Comment by BelegCufea** [comment]
I have cobbled together an update with options to select multiple chat frames for output. It is [v1.1.5-beta1](https://www.curseforge.com/wow/addons/pretty-reputation/files/4393511).

If you could be so kind as to try it out, I would appreciate it. It doesn't have any automation for selecting channels, but you can manually select which channels to use. If you only want to output to chat frames, please select 'None' from the general options.

I look forward to your reactions.

**Comment by Goss444** [comment]
This is great, thank you.  Would it be possible to add a dropdown with all possible chatframe1-n to send it to?

**Comment by BelegCufea** [comment]
That is an option, yes.

However, it is typically used to select a single output option, so you can choose to output to only one of the chat frames. I am aware that my implementation is cumbersome, but it provides the ability to output to multiple chat frames simultaneously. I attempted to simplify the structure in the beta2 version.

I aim to provide users with as much freedom as I am capable of with my limited abilities. Is it too distracting to leave it as it is? I would appreciate your opinion.

Thank you.

**Comment by Goss444** [comment]
What you have is great and I would recommend keeping it, I can see value in it. Like you said giving users options is great. My last suggestion was in addition to what you currently have in place.

**Comment by BelegCufea** [comment]
OK, I understand what you mean.

Unfortunately, I don't know how to transform a multichoice selection into a dropdown menu.
I will do some more research on this topic. In the meantime,

I will clean up my code and release a new version for others to try out this new addition.
If I find a way to change the multiselect into a dropdown, I will add it to future versions.

Thank you very much for the suggestion.
Have a nice day!
