### ISSUE TITLE
Request: Pin Reps

### ISSUE THREAD

**Issue by whoiskevinrich** [BelegCufea/PrettyReputation#11]
Sometimes I'm hunting for achievements, and want to track reputation right from login. Would it be possible to "favorite" or "pin" reps to the bar?

**Comment by BelegCufea** [comment]
OK, as I am currently not playing WoW, I did my best to implement the feature in the new version [v1.3.5](https://github.com/BelegCufea/PrettyReputation/releases/tag/v1.3.5).

**Comment by whoiskevinrich** [comment]
Wow... Thank you! I just saw the release.

**Comment by whoiskevinrich** [comment]
Looks good, but does require a reload when more than one rep is pinned 👍

**Comment by BelegCufea** [comment]
@whoiskevinrich OK, will look at it. Should be easy enough.

**Comment by BelegCufea** [comment]
Hope that the one line I added will do the job :-)
[v1.3.5a](https://github.com/BelegCufea/PrettyReputation/releases/tag/v1.3.5a) is on the way.

**Comment by BelegCufea** [comment]
OK, closing as done for now.

In case there is a problem, please open new issue :-)
