### ISSUE TITLE
Guild showing 0 / 3,000

### ISSUE THREAD

**Issue by Hyphie24** [BelegCufea/PrettyReputation#12]
No lua error, only happening with Guild.

Can test any changes if needed

![image](https://github.com/BelegCufea/PrettyReputation/assets/31455641/97105057-6cf8-4337-8bf9-0b5fe93fbd0a)

**Comment by BelegCufea** [comment]
Thanks for reporting this issue. It may be difficult for me to test it, as I am currently not playing WoW and all my characters are maxed in their guild.

I will try to look into it, though (soon &trade;).

**Comment by Hyphie24** [comment]
Just tell me what you think it may be and I can edit code and try it, have no problem doing that

**Comment by BelegCufea** [comment]
@Hyphie24 Hi, mate!

First of all, I assume you are in a guild and want to track guild reputation.

- Try enabling debug mode (checkbox on the "General" tab) and send me any text that appears in the chat after gaining guild reputation.
- Check if you have the "Track" -> "Guild" checkbox checked on the "General" tab (Did I use the word "check" too many times?).
- What locale are you using when running WoW? I haven't tried any other than English.

Have a nice day.

**Comment by Hyphie24** [comment]
Debug menu enabled, Guild was unchecked, set to "Auto Track", checked the guild box

English locale

![image](https://github.com/BelegCufea/PrettyReputation/assets/31455641/5a566173-0416-4d10-b233-773511e3d43f)

![image](https://github.com/BelegCufea/PrettyReputation/assets/31455641/f6812bff-ab3e-40b6-9e20-938fa896a75b)

The thing I did notice, the guild rep bar is also 0/3000

![image](https://github.com/BelegCufea/PrettyReputation/assets/31455641/fa215492-a292-41c5-9358-3b9681593a04)

if I go into the reputation panel, and manually track guild it shows the rep bar like normal

![image](https://github.com/BelegCufea/PrettyReputation/assets/31455641/1def2814-2e9d-4ec0-ac44-789cc46f2734)


I help maintain the addon "Pretty Reps" and tried to see if there was anything from that to use in this case, but not seeing anything

**Comment by BelegCufea** [comment]
Thanks for the report. I will look into this.

It seems I need to use the GetGuildInfo API to resolve the guild name. I need to avoid double-dipping into guild reputation changes.
Hmm, I will think about it for a bit.

**Comment by BelegCufea** [comment]
Hello again.

I just pushed a new commit with 3 lines that I hope can do "something" regarding this pesky error.

If you would be so kind, please download the [current code](https://github.com/BelegCufea/PrettyReputation/archive/refs/heads/master.zip) and try it.

I don't know exactly what it will do, but I hope it will do "something" :-)

**Comment by Hyphie24** [comment]
Will try out this afternoon after work and follow up with it

**Comment by Hyphie24** [comment]
HAZZAH! It works!

![image](https://github.com/BelegCufea/PrettyReputation/assets/31455641/4045983c-3bd2-4c1b-bfd5-67528747d220)

![image](https://github.com/BelegCufea/PrettyReputation/assets/31455641/cd6ad52d-c554-4abd-aa4c-c295c6e6f32a)


Thank you so much!

**Comment by BelegCufea** [comment]
@Hyphie24 Thanks for testing.

It seems there are still some problems with the faction table, but I won't touch it as I will definitely break it.
I need to rewrite the guild checks for those who do not want to see guild rep gains.

New version coming soon :-)

**Comment by BelegCufea** [comment]
OK. Where the hack my last comment from 3 days ago went?

@Hyphie24 Would you be so kind and test the latest [commit](https://github.com/BelegCufea/PrettyReputation/archive/refs/heads/master.zip)? I have made some minor changes to the code but can't test it myself.

Just look for any Lua errors :-)

Thank you very much.

**Comment by Hyphie24** [comment]
Looks to be working the same, the only difference is if you have "Auto Track" enabled but guild not enabled, the rep bar doesn't change (not sure if this is the intended result, if so then yes working correctly)

**Comment by BelegCufea** [comment]
Yep, that is intended. My reasoning is that when questing, you may not want to change tracked reputation every time you get some guild reputation.

Well, I will release it in its current state as a new version.

Thanks for reporting and for all the help.
