### ISSUE TITLE
Splash reputation error

### ISSUE THREAD

**Issue by jon-ault** [BelegCufea/PrettyReputation#15]
Still getting an error on splash reputation with 1.4.0c:

<details>

<summary>Lua error message</summary>

```
Message: Interface/AddOns/PrettyReputation/core.lua:500: attempt to perform arithmetic on field 'current' (a nil value)
Time: Fri Aug 16 16:12:55 2024
Count: 1
Stack: Interface/AddOns/PrettyReputation/core.lua:500: attempt to perform arithmetic on field 'current' (a nil value)
[string "@Interface/AddOns/PrettyReputation/core.lua"]:500: in function `processAllFactions'
[string "@Interface/AddOns/PrettyReputation/core.lua"]:568: in function <Interface/AddOns/PrettyReputation/core.lua:566>

Locals: factionInfo = <table> {
 change = 150
 new = false
 faction = "7th Legion"
}
trackFaction = nil
(for state) = <table> {
 Mana Creature = <table> {
 }
 Nethergarde Caravan = <table> {
 }
 Dark Talons = <table> {
 }
 Northsea Pirates = <table> {
 }
 The Iron Horde = <table> {
 }
 Grell = <table> {
 }
 Elemental, Fire = <table> {
 }
 Beast - Crocilisk = <table> {
 }
 Old Hillpaw = <table> {
 }
 The Enlightened = <table> {
 }
 Undead, Scourge = <table> {
 }
 Dark Kyrian = <table> {
 }
 Test Faction 2 = <table> {
 }
 Valarjar = <table> {
 }
 Bees = <table> {
 }
 Caverns of Time - Durnholde = <table> {
 }
 Hand of the Prophet = <table> {
 }
 Wrathgate Horde = <table> {
 }
 Gilneas = <table> {
 }
 Poen Gillbrack = <table> {
 }
 Mount - Taxi - Neutral = <table> {
 }
 CoT Scourge = <table> {
 }
 Akama's Trust = <table> {
 }
 Demon = <table> {
 }
 Everlook = <table> {
 }
 Friendly, Force Reaction 2 = <table> {
 }
 Zangarmarsh Banner (Horde) = <table> {
 }
 Monster, Prey = <table> {
 }
 Beast - Raptor = <table> {
 }
 Kirin'Var - Luminrath = <table> {
 }
 Friendly, Force Reaction 4 = <table> {
 }
 Protectorate = <table> {
 }
 Proudmoore Admiralty = <table> {
 }
 The High Hollows = <table> {
 }
 Dragonmaw Clan = <table> {
 }
 Moonstalker, Darkshore = <table> {
 }
 Shang Xi's Academy = <table> {
 }
 Friendly, Force Reaction 1 = <table> {
 }
 Silithid = <table> {
 }
 The Ashen Verdict = <table> {
 }
 Azaloth = <table> {
 }
 Revantusk Trolls = <table> {
 }
 Creature = <table> {
 }
 PLAYER, Orc = <table> {
 }
 Titan = <table> {
 }
 Kurenai = <table> {
 }
 PLAYER, Lightforged Draenei = <table> {
 }
 Wailing Caverns = <table> {
 }
 Nagrand Gronn = <table> {
 }
 Guardians of Hyjal = <table> {
 }
 HIllsbrad, Southshore Mayor = <table> {
 }
 The Sons of Lothar = <table> {
 }
 Fish Fellreed = <table> {
 }
 Maraudine = <table> {
 }
 Steamwheedle Preservation Society = <table> {
 }
 Impus = <table> {
 }
 Primalists = <table> {
 }
 Furbolg, Redfang = <table> {
 }
 Arcane Annihilator (DNR) = <table> {
 }
 The Black Prince = <table> {
 }
 Inciter Trigger 3 = <table> {
 }
 Bloodmaul Clan = <table> {
 }
 Makrura = <table> {
 }
 Soridormi = <table> {
 }
 PLAYER, Worgen = <table> {
 }
 Frostfire Ogres = <table> {
 }
 Silithid Attackers = <table> {
 }
 Cobalt Assembly = <table> {
 }
 Test = <table> {
 }
 Honor Hold = <table> {
 }
 Brawl'gar Arena (Season 1) = <table> {
 }
 Shadowsilk Poacher = <table> {
 }
 Ratchet = <table> {
 }
 Enemy = <table> {
 }
 Dark Iron Dwarves = <table> {
 }
 Sha'tari Defense = <table> {
 }
 Classic = <table> {
 }
 Murloc = <table> {
 }
 Friendly, New = <table> {
 }
 Craig's Squirrels = <table> {
 }
 Tina Mudclaw = <table> {
 }
 Cenarion Circle = <table> {
 }
 The Scryers = <table> {
 }
 Gnoll - Redridge = <table> {
 }
 Wendigo = <table> {
 }
 The Wyrmrest Accord = <table> {
 }
 Cutwater Corsairs = <table> {
 }
 Holiday - Generic = <table> {
 }
 Elemental, Water = <table> {
 }
 Tortollan Seekers = <table> {
 }
 Quilboar, Deathshead = <table> {
 }
 The Nightfallen = <table> {
 }
 Gorgrond Goren = <table> {
 }
 Nazmani = <table> {
 }
 Stone Legion = <table> {
 }
 The Frostborn = <table> {
 }
 Monster Spar = <table> {
 }
 Tushui Pandaren = <table> {
 }
 Blue = <table> {
 }
 Neutral, Force Reaction 1 = <table> {
 }
 Tormmok = <table> {
 }
 Leotheras Demon IV = <table> {
 }
 Sholazar Basin = <table> {
 }
 Shadow Council = <table> {
 }
 Death's Advance = <table> {
 }
 Shadow Council Covert = <table> {
 }
 Vrykul (Ancient Siprit 2) = <table> {
 }
 
```

</details>

**Comment by BelegCufea** [comment]
I wasn’t able to replicate the error on my end despite multiple attempts—believe me, I tried.

Additionally, I don't think the issue is related to the "Splash" reputations feature. It seems that the factions table isn't populating correctly on your side.

That said, could you please disable the "Splash" reputations option and test the addon again?

If the issue persists, would you be willing to try some temporary fixes with Debug mode enabled? I'll push them into a new branch for testing.

**Comment by jon-ault** [comment]
With splash reputation turned off I don't get an error.

I'd be willing to try some test builds.

**Comment by jon-ault** [comment]
I hopped on my main & did a world quest in each of several different expansions (Shadowlands, BfA, Legion, WoD) with splash rep turned on and couldn't duplicate the error; I put a print statement at the beginning of processAllFactions() to verify it was getting called since no splash reps were being reported. I even did a 7th Legion quest which is what I've been doing on the alt that's been getting those errors. I wonder if this has something to do with the character getting the errors being a boosted character & if that's somehow affecting the reputations that WoW reports - this level 70 toon hasn't been to Shadowlands or the Dragon Isles at all yet.

I also created a new Alliance toon & verified that splash reps were working correctly on a character that could actually get some.

**Comment by BelegCufea** [comment]
That's quite weird indeed. It seems to be a pretty niche issue.

Before I start guessing at potential solutions, could you please install the [DevTool](https://www.curseforge.com/wow/addons/devtool) addon and enable the `Debug` option in Pretty Reputation (it’s the last option on the General tab)? After enabling debugging, make sure to `/reload` your UI.

Once that's done, type `/dev` into the chat to open the DevTool main window. You should see an entry called "Pretty Reputation_Factions". Click on it to expand the information and drill down into some of the "info" entries for different factions. It should look something like this:

![image](https://github.com/user-attachments/assets/12e34e13-1d63-4ba9-b7ee-a3bd6220a8f4)

Please post a screenshot here, as it could help me a lot in diagnosing the issue.

Thanks in advance!

**Comment by jon-ault** [comment]
Here's a few screenshots. One thing I noticed is that none of the main Shadowlands factions are listed (Venthyr, Necrolords, Kyrian, Night Fae) but at least some of the Dragon Isles factions are (such as Valdrakken Accord and Iskaara Tuskarr). But that also is the case for a new character.
![1 - 7th legion](https://github.com/user-attachments/assets/e6812ae2-0601-48c9-8fa1-11269189c5f9)
![2 - Proudmoore](https://github.com/user-attachments/assets/39a61391-49ab-4b2b-b126-b1b62f7c638b)
![3 - vrykul](https://github.com/user-attachments/assets/9365945a-d081-421e-8b1b-98255c944c59)

**Comment by jon-ault** [comment]
OK, I found something interesting. The character that's getting the errors has one more faction than my main. I tracked down the extra faction and it doesn't look right at all:
![Screenshot 2024-08-17 at 1 08 14 AM](https://github.com/user-attachments/assets/5b33a32e-43a1-445e-8a5a-a28464a6ccf8)

I spot checked a few other characters and none of them have this "Inactive" faction listed in DevTool.

**Comment by BelegCufea** [comment]
I know about that pesky faction. I was certain I had dealt with it for good, but apparently not.

Could you please change line 144 of `core.lua`

from
```lua
    if factionData and factionData.name and factionData.factionID then
```

to 
```lua
    if factionData and factionData.name and factionData.factionID and factionData.factionID ~= 0 then
```

I hope this simple change resolves the issue. If it does, I’ll go ahead and release the update.

Thank you so much for your help!

**Comment by jon-ault** [comment]
Looks good. I'm no longer getting the errors and the "Inactive" faction is not listed by DevTool now.

**Comment by jon-ault** [comment]
One other thing I noticed. When I turn in a quest on a new character that generates some splash reputation, processAllFactions() appears to be getting called once for each faction that had an increase. Here's a new Human character turning in his first quest in Northshire Valley :
![Screenshot 2024-08-17 at 12 10 15 PM](https://github.com/user-attachments/assets/d49fd6bf-0805-4389-a7db-27a6797f4c45)
I added that print statement at the beginning of the function.
Edit: never mind, I see now those aren't splash reputation gains but are actually reported as gains by the game & show up even if splash rep is turned off.

**Comment by BelegCufea** [comment]
OK, thanks for testing.

And about that multiple callings ... that is why "Splash" option is soo CPU heavy.
BTW it only works on two faction groups in WotLK, {[Alliance Vanguard](https://www.wowhead.com/faction=1037/alliance-vanguard)/[Horde Expedition](https://www.wowhead.com/faction=1052/horde-expedition)}. It is not really usefull since then. Maybe I should hide it or something, IDK :-(

**Comment by jon-ault** [comment]
I didn't realize how rare those splash reputation occurrences really were, I thought they happened a lot more frequently than that.
