### ISSUE TITLE
[Feature Request] Order Favourites by Expansion

### ISSUE THREAD

**Issue by fronbow** [BelegCufea/PrettyReputation#16]
Hiya

Awesome addon - it looks like a good replacement for [Reputation Bars](https://legacy.curseforge.com/wow/addons/reputation-bars)

As the title says, is it possible to order the Favourites option page by expansion as I tend to watch whichever expansion my character is playing.

(Also, why are a lot of them in red?)

Cheers

**Comment by BelegCufea** [comment]
# v1.4.0c (16.8.2024)

## Fix
- Blizz messing with Reputation panel again

**Overview:**
This is a (let's hope temporary) fix for the issue where Blizzard isn't listing all valid reputations in the Reputation panel. **WTF Blizz... AGAIN!**

**Changes:**
All unlisted reputations, some of which are quite weird, now appear in red within the "Favorites" section and the "Test" drop-down box. This is a temporary workaround to ensure you can still see and track those reputations until Blizzard resolves the issue.

**Note:**
Please be aware that the "Show splash reputation" feature now has to parse over 600 reputations each time any reputation changes. This might cause a slight performance impact, potentially reaching tens of milliseconds.

**Clean-up:**
If I find the time, I promise I'll clean up the favorite reputations picking process!
