### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by jisamcom** [BelegCufea/PrettyReputation#17]
5x PrettyReputation/core.lua:245: bad argument #2 to 'max' (number expected, got nil)
[string "=[C]"]: in function `max'
[string "@PrettyReputation/core.lua"]:245: in function `rgbToHsv'
[string "@PrettyReputation/core.lua"]:285: in function `interpolateColors'
[string "@PrettyReputation/core.lua"]:321: in function `GetFactionColors'
[string "@PrettyReputation/core.lua"]:531: in function `getRepInfo'
[string "@PrettyReputation/core.lua"]:173: in function `setupFaction'
[string "@PrettyReputation/core.lua"]:186: in function `setupFactions'
[string "@PrettyReputation/core.lua"]:798: in function <PrettyReputation/core.lua:796>
[string "=[C]"]: ?
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ack/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@!mMT_MediaPack/libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
(*temporary) = 1
(*temporary) = nil
(*temporary) = 0
(*temporary) = "number expected, got nil"

**Comment by BelegCufea** [comment]
@jisamcom Hmm, I could not replicate that error, and it seems strange as it would mean the Renown `From` color does not have a green component. Can you try to reset a profile? Or create new one if you want to keep current one?

**Comment by jisamcom** [comment]
after reset profile, it looks like resolved. = )
