### ISSUE TITLE
Lua error on login (latest master branch)

### ISSUE THREAD

**Issue by filliph** [BelegCufea/PrettyReputation#7]
```
14x PrettyReputation/core.lua:532: attempt to index field 'paragon' (a nil value)
[string "@PrettyReputation/core.lua"]:532: in function <PrettyReputation/core.lua:529>
```

**Comment by BelegCufea** [comment]
Thanks again.

Will look into it. Still working on hiding reward bag from on-screen bars :-)

**Comment by BelegCufea** [comment]
Pushed a commit into `master` to apply dirty fix for the error (so you can use latest code).

I don't know if there are more errors as I need to test it once I gain new paragon level on one of my chars (hope it will be soon).

Sorry for inconvenience.

**Comment by filliph** [comment]
New issue when turning in quests in the Forbidden Reach:
```
9x PrettyReputation/core.lua:540: attempt to call local 'event' (a string value)
[string "@PrettyReputation/core.lua"]:540: in function `UpdateReward'
[string "@PrettyReputation/core.lua"]:433: in function `UpdateBars'
[string "@PrettyReputation/core.lua"]:513: in function <PrettyReputation/core.lua:509>
```

**Comment by filliph** [comment]
Ahh, it's a string concatenation issue 😄 `Debug:Info(v.info.reward, event ": " ..v.info.name)` is missing the `..` 😄

**Comment by filliph** [comment]
There's also a typo, `if v.info.poragon then` should be `if v.info.paragon then`

**Comment by filliph** [comment]
`local _, _, _, hasRewardPending = C_Reputation.GetFactionParagonInfo(v.info.factionID)` might need to be `local _, _, _, hasRewardPending = C_Reputation.GetFactionParagonInfo(v.info.factionId)` since I think Lua table keys are case sensitive - this caused another error 

```
9x PrettyReputation/core.lua:541: Usage: local currentValue, threshold, rewardQuestID, hasRewardPending, tooLowLevelForParagon = C_Reputation.GetFactionParagonInfo(factionID)
[string "=[C]"]: in function `GetFactionParagonInfo'
[string "@PrettyReputation/core.lua"]:541: in function <PrettyReputation/core.lua:533>
```

**Comment by BelegCufea** [comment]
Ahh, tyvm. That part of code triggers when reward for paragon is ready. Was not eligable for this from the time I wrote that code.

Will implement your fixes right away.

**Comment by BelegCufea** [comment]
I just released version [1.3.0-beta2](https://github.com/BelegCufea/PrettyReputation/releases/tag/v1.3.0-beta2).

It has been somewhat tested (though you know how my tests go).

If you are okay with it and don't find any more errors, I will close this issue.

**Comment by filliph** [comment]
Looks good to me, no errors on load or when gaining rep (both Paragon and "normal") 😄

**Comment by BelegCufea** [comment]
OK. Thanks again.
