### ISSUE TITLE
"Faction not found - Guild" + Lua error

### ISSUE THREAD

**Issue by filliph** [BelegCufea/PrettyReputation#8]
The weird thing about this is that I've gained reputation with my guild with no issues before. This particular issue happened when a < 70 character turned in the quest [Open Orientation](https://www.wowhead.com/quest=72585/open-orientation).

This character has been in the guild for about a year now, so it's definitely not new to having a guild.

```
[07:06:24 PM] Faction not found - Guild [change: +138]
```

```
3x PrettyReputation/core.lua:507: attempt to index field '?' (a nil value)
[string "@PrettyReputation/core.lua"]:507: in function <PrettyReputation/core.lua:501>

Locals:
(*temporary) = <function> defined @PrettyReputation/debug.lua:8
(*temporary) = <table> {
 Info = <function> defined @PrettyReputation/debug.lua:8
}
(*temporary) = "Guild"
(*temporary) = nil
(*temporary) = "Guild"
(*temporary) = "attempt to index field '?' (a nil value)"
info = <table> {
 change = 125
 new = true
 faction = "Guild"
}
```

(Cropped the BugSack Locals block to what I believe is the most relevant information.)

**Comment by BelegCufea** [comment]
Thanks (again) for reporting.

Will look into it.

**Comment by BelegCufea** [comment]
I made some changes to the code to prevent error messages from being thrown.

Please can you try the latest `master` version and let me know if you still receive a `Faction not found - Guild` message in chat. I don't know If this error only occurs with a particular quest though.

Thank you!

**Comment by filliph** [comment]
No more Lua errors at least, but the `[05:00:29 PM] Faction not found - Guild [change: +137]` still shows up when you do any of the "Renown Supplies" quests from when you hit certain renown thresholds.

**Comment by BelegCufea** [comment]
OK. Thanks for testing.

Will make a bugfix and release new version ... soon (TM) :-)

**Comment by BelegCufea** [comment]
I still have no idea why Blizzard is doing it, but I moved the message to the Debug section so it won't bother users anymore. :)

I haven't tested the latest commit yet, but I will do so tomorrow. It should work, but with my dysgraphia, I could have made some spelling mistakes again (sorry).

And once again, thank you for your help!

**Comment by filliph** [comment]
No problem, will test it further tomorrow and let you know if it happens again 😄

**Comment by BelegCufea** [comment]
FYI, it seems to be working fine under normal conditions. However, I do not have any characters in a guild that is leveling renown in DF, so I cannot test that specific problem.

**Comment by BelegCufea** [comment]
[filliph](https://github.com/filliph), I have a small request.

Could you please turn on Debug mode in my addon (in the General panel) and also turn on the "Reputation" option in the Settings of the Blizzard chat window? To do this, right-click the chat tab, select Settings, go to the "Other" section, and make sure "Reputation" is checked.

This will help me to better understand the problem.

Thank you!

**Comment by filliph** [comment]
I've not been able to replicate it just yet, it looks like something that doesn't happen that often 🤔

**Comment by BelegCufea** [comment]
Ok, I know it is a pain in the ... ehm ... to test it :-)

I will release it as it is and will monitor it as well.

Thank you for your time and help.
